[package]
name = "lovely-core"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.153"
libloading = "0.8.3"
once_cell = "1.19.0"
sha2 = "0.10.8"
toml = "0.8.10"
walkdir = "2.5.0"
regex-lite = "0.1.5"
wildmatch = "2.3.0"
serde = { version = "1.0.197", features = ["derive"] }