[package]
name = "lovely-mac"
version = "0.1.0"
edition = "2021"

[lib]
name = "lovely"
crate-type = ["cdylib"]

[dependencies]
lovely-core = { version ="*", path = "../lovely-core" }

dirs = "5.0.1"
getargs = "0.5.0"
libc = "0.2.153"
once_cell = "1.19.0"
widestring = "1.0.2"
ctor = "0.2.7"
